# Generated by Django 5.2 on 2025-04-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FunctionalityApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pro',
        ),
    ]
